### ISSUE TITLE
Problems after upadte packages

### ISSUE THREAD

**Issue by KZiemian** [abo-abo/swiper-helm#10]
After today update, when I use swiper-helm I can only go between first and last entry of list (by C-n, C-p). Also fuzzy matching don't work: if I have line with ,,swiper thing'', ,,swt'' don't find it, you can type ,,swi thi'', that works. Probably new version of dependencies are not back compatible with it.

Problems seems to hard for my knowledge of elisp and Emacs packages.

**Comment by abo-abo** [comment]
Please try re-installing. Everything works fine for me with helm-20160302.947, swiper-helm-20151116.330.

**Comment by KZiemian** [comment]
Thank you, all fine now. I just don't think about easiest solution. My
fault.

czw., 3.03.2016 o 11:12 użytkownik Oleh Krehel <notifications@github.com>
napisał:

**Comment by abo-abo** [comment]
glad it worked out:)
