### ISSUE TITLE
wrong-type-argument error when using swiper-helm

### ISSUE THREAD

**Issue by iswanz** [abo-abo/swiper-helm#11]
My beloved swiper-helm has stopped working since a recent update. Swiper works fine.

I get the error:
Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil)

The swiper-helm buffer narrows as a I type, but when I try and move the selection (using any of the arrow keys) it jumps to the bottom of the swiper-helm buffer and then won't move.

Some debug information:
In GNU Emacs 25.1.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2016-08-10 built on
Repository revision: e13c5467fc0c08c6875653df56b8b54185d0c4cc
Windowing system distributor 'The X.Org Foundation', version 11.0.11803000
System Description:	Ubuntu 16.04.1 LTS

Recent messages:
Debug (ox-odt): No OpenDocument schema files installed
[yas] Reloaded everything (snippets will load just-in-time)....
Init file processed completely
For information about GNU Emacs and the GNU system, type C-h C-a.
Starting new Ispell process /usr/bin/aspell with default dictionary...
Symbolic link to Git-controlled source file; follow link? (y or n) y
Making helm-display-function local to *swiper* while let-bound!
Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil)
Mark set

Thanks for your help!

**Comment by abo-abo** [comment]
`swiper-helm` hasn't been updated for months. I just checked with `helm-20160808.2223` and Emacs 25, `swiper-helm` still works fine: narrowing works and the arrow keys work.

> Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil)

This error does not originate in `swiper-helm` source. Just update `helm`, hopefully it goes away.

**Comment by dakra** [comment]
I have the same problem.
`helm` works fine but moving up/down in `swiper-helm` is not working correctly.

I tried it with emacs-24 and now emacs-25.1.
`helm` version is `20160814.522`.

**Comment by abo-abo** [comment]
[install-deps.txt](https://github.com/abo-abo/swiper-helm/files/419859/install-deps.txt)

Try to reproduce with:

    emacs-24.5 -Q -l install-deps.txt

`M-x swiper-helm`,  `t h`, `C-n C-p`. Works fine for me.

**Comment by dakra** [comment]
Hmm.. when I start with `emacs -Q -l install-deps.txt` `swiper-helm` works perfect so I guess it's not a `swiper-helm` issue.
Any tips how I could find out what's causing this? Starting with `--debug-init` (or starting normal) doesn't show any error messages.

**Comment by abo-abo** [comment]
@dakra Thanks for confirming. 

> Any tips how I could find out what's causing this?

This type of bug is easiest to solve by bisecting your config. Using `install-deps.txt` is like commenting out your whole config. What you need to do now is to comment out just about a half, while keeping `swiper-helm` loading. Check if the bug is there. Either way, you know in which half of the config it is. Now take that half and half it once more. Keep going until you find the problem line.

**Comment by dakra** [comment]
Just a quick update if someone has the same problem.
For me it was not a particular package or misconfiguration.
I just had to recompile my packages and then it worked.
So `(byte-recompile-directory package-user-dir nil 'force)` fixed it for me ¯\\\_(ツ)\_/¯

**Comment by abo-abo** [comment]
> ¯\_(ツ)_/¯

^. Problem solved:)

**Comment by iswanz** [comment]
Sorry for delay in responding. I tried @dakra 's suggestion of using:

`(byte-recompile-directory package-user-dir nil 'force)`

and that didn't work for me, so I went through @abo-abo 's process of bisecting my .emacs and found that the problem (for me) was [minimap](http://elpa.gnu.org/packages/minimap.html). By adding that package to @abo-abo 's minimal install script I can reproduce the error. I've attached the updated script, which I ran using:

`emacs -Q -l install-deps-with-minimap.txt`

[install-deps-with-minimap.txt](https://github.com/abo-abo/swiper-helm/files/425865/install-deps-with-minimap.txt)

**Comment by iswanz** [comment]
The same problem occurs for me with [helm-swoop](https://github.com/ShingoFukuyama/helm-swoop). A bit of duck-ducking found that a [similar issue](https://github.com/ShingoFukuyama/helm-swoop/issues/64) was reported with that package and [neotree](https://github.com/jaypei/emacs-neotree).
