### ISSUE TITLE
does not work on pdf files opened with pdf-tools

### ISSUE THREAD

**Issue by bishesh** [abo-abo/swiper-helm#13]
I can use isearch-forward or isearch-backward on my pdf files.
However, I can't use swiper-helm as trying it does not show normal texts as the suggestions in *swiper* buffer.

**Comment by abo-abo** [comment]
This can't be done easily. `isearch-forward` doesn't work for pdf, it's `pdf-tools` replacement which is less powerful that regular `isearch-forward`.

Open an issue for `pdf-tools` to get a more complete text interface if you want. There already is one, probably. It's a difficult problem.
