### ISSUE TITLE
wrong-number-of-arguments

### ISSUE THREAD

**Issue by stef204** [abo-abo/swiper-helm#14]
Hi,

Full error is: wrong-number-of-arguments (1 . 1) 2

[Trace](https://gist.github.com/stef204/d585d94431a2ef54244374dfe61050b5)

Is this still working/compatible?

emacs 25.3 on Linux.
swiper-helm  20151116.330
swiper 20180124.1142
ivy  20180124.1127

**Comment by abo-abo** [comment]
Thanks.

**Comment by stef204** [comment]
Curious to know if you will try to fix or not. I happen to really like this (as many other users) and well, miss it.
