### ISSUE TITLE
Cannot open load file: No such file or directory, helm-match-plugin

### ISSUE THREAD

**Issue by timmli** [abo-abo/swiper-helm#15]
I'm getting this when starting `swiper-helm`. 

Emacs 25.3
helm 20180201.2127
swiper-helm 0.1.0

**Comment by timmli** [comment]
Works fine with the newest version on Melpa (20180131.944).
Maybe it's time to update Melpa stable?

Thanks for sharing this package!

**Comment by abo-abo** [comment]
I tagged 0.2.0. Your issue should be fixed, thanks.
