### ISSUE TITLE
Error due to ivy dependency upgrade

### ISSUE THREAD

**Issue by stef204** [abo-abo/swiper-helm#17]
Getting a new error after upgrading ivy to 20180315.1446
ivy is a dependency of swiper, itself a dependency of helm-swiper.

[Trace](https://gist.github.com/stef204/d660ae085df0476451bd123e5c6e741c)

Emacs 26.0.91
Linux x86_64

**Comment by abo-abo** [comment]
Looks like package.el intstall error; try to uninstall/reinstall.

**Comment by stef204** [comment]
I deleted and reinstalled the full chain (swiper-helm, which reinstalled the deps swiper and ivy) and all is fine now. Thanks.

**Comment by abo-abo** [comment]
No problem.
