### ISSUE TITLE
Picking up symbol at point

### ISSUE THREAD

**Issue by maindoor** [abo-abo/swiper-helm#18]
I am trying to replace helm-swoop with swiper-helm, facing a couple of nits.
Can swiper-helm start off by picking up symbol at point (like what helm-swoop does ?)

**Comment by abo-abo** [comment]
Press <kbd>M-n</kbd> to do this.

**Comment by hmehra** [comment]
@abo-abo M-n does not work for special chars like :: which is frequent in C++ code. Any other alternatives?

**Comment by abo-abo** [comment]
@hmehra You can use <kbd>M-j</kbd> with `swiper`. `swiper-helm` is in maintenance, I don't actively work on it. But feel free to port <kbd>M-j</kbd> from `swiper` if you like, I'll merge the PR.

Closing this issue, since the question is answered.
