### ISSUE TITLE
Emacs frame flashing while using swiper-helm

### ISSUE THREAD

**Issue by BruceCST** [abo-abo/swiper-helm#20]
Hello, this is my first bug report, if anything I should mention or upload or format wrong please let me know, thanks a lot!

#### Description
Emacs refresh the frame when input any letters while using swiper-helm

#### Observed behavior
Emacs frame flashing while using swiper-helm

#### Expected behavior
Do not flash

#### System info
OS: Arch Linux
Emacs: 26.1
Spacemacs: V.0.300.0
Spacemacs branch: Develop
Editing style: emacs

**Comment by abo-abo** [comment]
Hi, I haven't made any changes to the package in 6 months. And I can't reproduce the bug with the latest version of Helm. I see you're using Spacemacs; please consider reporting the bug there, maybe it's config-related.

**Comment by BruceCST** [comment]
Ok then, thank you all the same, have a nice day!
