### ISSUE TITLE
swiper-helm complains about (void-variable ivy-format-functions-alist)

### ISSUE THREAD

**Issue by adl** [abo-abo/swiper-helm#22]
Installing `swiper-helm` from MELPA show the following messages:

```
Compiling file /home/adl/.emacs.d/elpa/swiper-20190604.1008/swiper.el at Tue Jun  4 14:19:05 2019
Entering directory ‘/home/adl/.emacs.d/elpa/swiper-20190604.1008/’
swiper.el:1195:15:Warning: reference to free variable
    ‘ivy-format-functions-alist’
swiper.el:1195:15:Warning: assignment to free variable
    ‘ivy-format-functions-alist’

In end of data:
swiper.el:1517:1:Warning: the function ‘ivy--insert-symbol-boundaries’ is not
    known to be defined.
```

Then trying to execute `M-x swiper-helm` simply results in 

```
helm-M-x: Symbol’s value as variable is void: ivy-format-functions-alist
Debugger entered--Lisp error: (void-variable ivy-format-functions-alist)
  byte-code("\301\010\235\203\013\0\010\210\202\017\0\301\010B\020\302\207" [ivy-format-functions-alist (swiper-multi . swiper--all-format-function) nil] 2)
  #<subr require>(swiper)
  apply(#<subr require> swiper)
  require(swiper)
  eval-buffer(#<buffer  *load*> nil "/home/adl/.emacs.d/elpa/swiper-helm-20180131.1744/swiper-helm.el" nil t)  ; Reading at buffer position 1331
  load-with-code-conversion("/home/adl/.emacs.d/elpa/swiper-helm-20180131.1744/swiper-helm.el" "/home/adl/.emacs.d/elpa/swiper-helm-20180131.1744/swiper-helm.el" nil t)
  autoload-do-load((autoload "swiper-helm" "`isearch' with an overview using `helm'.\nWhen non-nil, INITIAL-INPUT is the initial search pattern.\n\n(fn &optional INITIAL-INPUT)" t nil) swiper-helm)
  command-execute(swiper-helm)
```

**Comment by abo-abo** [comment]
Please reinstall `ivy` and restart Emacs. This is a recurring package.el / MELPA issue: `swiper` depends on `ivy` but an old version of `ivy` is used to byte-compile the new version of `swiper` when doing an upgrade.

Tagging @purcell, perhaps this is an issue with other packages as well. I've seen this one with `ivy` / `swiper` at least three times over the last few years.

**Comment by adl** [comment]
Indeed I had ivy-20190214.103 installed.  Upgrading all packages solved this.  Sorry for the noise.

**Comment by purcell** [comment]
> Please reinstall `ivy` and restart Emacs. This is a recurring package.el / MELPA issue: `swiper` depends on `ivy` but an old version of `ivy` is used to byte-compile the new version of `swiper` when doing an upgrade.
> 
> Tagging @purcell, perhaps this is an issue with other packages as well. I've seen this one with `ivy` / `swiper` at least three times over the last few years.

This would be a `package.el` thing, not a MELPA thing.
