### ISSUE TITLE
Problem in swiper-helm: swiper--anchor variable is void

### ISSUE THREAD

**Issue by KZiemian** [abo-abo/swiper-helm#9]
After last update I can't use swiper-helm because swiper--anchor variable is void. I use GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.16.6) on Linux Fedora 23. I check last issues and it seems that I have all updates of swiper-helm.el.

I don't know what to do and live without swiper-helm is quite hard;).

**Comment by abo-abo** [comment]
Thanks.

**Comment by KZiemian** [comment]
Thank you:).

**Comment by KZiemian** [comment]
This solve most of a problem but one strange thing. Problem with swiper--anchor is void stay until, I evaluated buffer swiper-helm.el. When I just evaluate defvar swiper--helm and swiper--len, I have error ,,Format specifier doesn't much argument type''.

**Comment by abo-abo** [comment]
I think restarting Emacs should solve that problem.

**Comment by KZiemian** [comment]
Thank you, after another update everything work fine:).
